theme: jekyll-theme-minimal
title: z3's homepage
description: Bookmark this to keep an eye on my project updates!
plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
